
-- V19: Expand Doctor Schedules with 15-minute intervals from 7:00 to 17:00
-- Covering dates from 2026-04-20 to 2026-05-31 to support dynamic date picker for many days

INSERT INTO doctor_schedules (doctor_id, work_date, start_time, end_time, created_at)
WITH RECURSIVE dates AS (
    SELECT '2026-04-20' AS d
    UNION ALL
    SELECT DATE_ADD(d, INTERVAL 1 DAY) FROM dates WHERE d < '2026-05-31'
),
nums AS (
    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL 
    SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL 
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL 
    SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL 
    SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL 
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL 
    SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL 
    SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39
),
slots AS (
    SELECT 
        TIME(ADDTIME('07:00:00', SEC_TO_TIME(n * 900))) as start_t,
        TIME(ADDTIME('07:15:00', SEC_TO_TIME(n * 900))) as end_t
    FROM nums
)
SELECT 
    d.id,
    dt.d,
    s.start_t,
    s.end_t,
    NOW()
FROM doctors d
CROSS JOIN dates dt
CROSS JOIN slots s
WHERE NOT EXISTS (
    SELECT 1 FROM doctor_schedules ds 
    WHERE ds.doctor_id = d.id 
    AND ds.work_date = dt.d 
    AND ds.start_time = s.start_t
);
